package ${package.Entity};

<#list table.fields as field>
    <#if field.keyFlag>
        <#assign keyPropertyName="${field.propertyName}"/>
    </#if>
</#list>
import lombok.Data;
import java.io.Serializable;
<#if entitySerialVersionUID>
import java.io.Serial;
</#if>

/**
 * ${table.comment!} DTO
 * Custom template generated by MyBatis-Plus Generator UI
 */
@Data
<#if entitySerialVersionUID>
public class ${entity}DTO implements Serializable {
<#else>
public class ${entity}DTO {
</#if>
<#if entitySerialVersionUID>
    @Serial
    private static final long serialVersionUID = 1L;
</#if>

<#list table.fields as field>
    /**
     * ${field.comment}
     */
    private ${field.propertyType} ${field.propertyName};

</#list>
}
